services:
  amadeus:
    build:
      context: .
      dockerfile: ./docker/uv/Dockerfile
    container_name: amadeus
    ports:
      - "8000:8000"
    volumes:
      - ./assets:/app/assets
    restart: unless-stopped
